# ========================
# 🔐 GERAIS (comuns a todos os robôs)
# ========================
telegram_token = "6357672250:AAFfn3fIDi-3DS3a4DuuD09Lf-ERyoMgGSY"
gmail_app_password = "anoe gegm boqj ldzo"
email_sender = "avisoscanal1milhao@gmail.com"

# ========================
# 📈 CURTO PRAZO
# ========================
telegram_chat_id_curto = "-1002198655576"
email_recipient_curto = "xande5@hotmail.com"
supabase_url_curto = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_curto = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbHdpZnZya2NxbXJ6Z3B2aHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTU1NDcsImV4cCI6MjA3NTY3MTU0N30.E2hmdWSKG5_Qt3btbiTISqB7lPXH5PY-rrj9BjiP1y8"

# ========================
# ⚡ CURTÍSSIMO PRAZO
# ========================
telegram_chat_id_curtissimo = "-1002198655576"
email_recipient_curtissimo = "xande5@hotmail.com"
supabase_url_curtissimo = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_curtissimo = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbHdpZnZya2NxbXJ6Z3B2aHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTU1NDcsImV4cCI6MjA3NTY3MTU0N30.E2hmdWSKG5_Qt3btbiTISqB7lPXH5PY-rrj9BjiP1y8"

# ========================
# 🏛️ CLUBE
# ========================
telegram_chat_id_clube = "-1002198655576"
email_recipient_clube = "xande5@hotmail.com"
supabase_url_clube = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_clube = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbHdpZnZya2NxbXJ6Z3B2aHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTU1NDcsImV4cCI6MjA3NTY3MTU0N30.E2hmdWSKG5_Qt3btbiTISqB7lPXH5PY-rrj9BjiP1y8"

# ========================
# 📉 LOSS CURTO
# ========================
telegram_chat_id_losscurto = "-1002198655576"
email_recipient_losscurto = "xande5@hotmail.com"
supabase_url_loss_curto = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_loss_curto = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbHdpZnZya2NxbXJ6Z3B2aHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTU1NDcsImV4cCI6MjA3NTY3MTU0N30.E2hmdWSKG5_Qt3btbiTISqB7lPXH5PY-rrj9BjiP1y8"

# ========================
# ⚡ LOSS CURTÍSSIMO
# ========================
telegram_chat_id_losscurtissimo = "-1002198655576"
email_recipient_losscurtissimo = "xande5@hotmail.com"
supabase_url_loss_curtissimo = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_loss_curtissimo = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbHdpZnZya2NxbXJ6Z3B2aHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTU1NDcsImV4cCI6MjA3NTY3MTU0N30.E2hmdWSKG5_Qt3btbiTISqB7lPXH5PY-rrj9BjiP1y8"

# ========================
# 🏛️ LOSS CLUBE
# ========================
telegram_chat_id_lossclube = "-1002198655576"
email_recipient_lossclube = "xande5@hotmail.com"
supabase_url_loss_clube = "https://kflwifvrkcqmrzgpvhqe.supabase.co"
supabase_key_loss_clube = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmbHdpZnZya2NxbXJ6Z3B2aHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwOTU1NDcsImV4cCI6MjA3NTY3MTU0N30.E2hmdWSKG5_Qt3btbiTISqB7lPXH5PY-rrj9BjiP1y8"
